# Generated by Django 4.2.26 on 2025-11-24 22:32

from django.db import migrations, models
import regulatory_app.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RemoteDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_text", models.TextField(blank=True, null=True)),
                (
                    "content_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=regulatory_app.models.upload_to_fetched,
                    ),
                ),
                ("content_size", models.BigIntegerField(blank=True, null=True)),
                ("entities", models.JSONField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, null=True)),
                ("severity", models.FloatField(blank=True, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
